version: '3.9'

x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 20m
      max-file: '3'
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  nginx:
    image: nginx:1.25-alpine
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      placement:
        constraints: [node.role == worker]
    <<: *logging
